// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRecentProject(arg1, arg2) {
  return window['go']['core']['App']['AddRecentProject'](arg1, arg2);
}

export function AutoSave(arg1) {
  return window['go']['core']['App']['AutoSave'](arg1);
}

export function BlendImages(arg1) {
  return window['go']['core']['App']['BlendImages'](arg1);
}

export function ClearAutoSave() {
  return window['go']['core']['App']['ClearAutoSave']();
}

export function ClearRecentProjects() {
  return window['go']['core']['App']['ClearRecentProjects']();
}

export function CreateProject(arg1, arg2, arg3) {
  return window['go']['core']['App']['CreateProject'](arg1, arg2, arg3);
}

export function EditImage(arg1) {
  return window['go']['core']['App']['EditImage'](arg1);
}

export function EnhancePrompt(arg1) {
  return window['go']['core']['App']['EnhancePrompt'](arg1);
}

export function ExportImage(arg1, arg2) {
  return window['go']['core']['App']['ExportImage'](arg1, arg2);
}

export function GenerateImage(arg1) {
  return window['go']['core']['App']['GenerateImage'](arg1);
}

export function GetProjectMeta(arg1) {
  return window['go']['core']['App']['GetProjectMeta'](arg1);
}

export function GetRecentProjects() {
  return window['go']['core']['App']['GetRecentProjects']();
}

export function LoadAutoSave() {
  return window['go']['core']['App']['LoadAutoSave']();
}

export function LoadProject() {
  return window['go']['core']['App']['LoadProject']();
}

export function LoadProjectFromPath(arg1) {
  return window['go']['core']['App']['LoadProjectFromPath'](arg1);
}

export function LoadSettings() {
  return window['go']['core']['App']['LoadSettings']();
}

export function RemoveBackground(arg1) {
  return window['go']['core']['App']['RemoveBackground'](arg1);
}

export function RemoveRecentProject(arg1) {
  return window['go']['core']['App']['RemoveRecentProject'](arg1);
}

export function SaveProject(arg1, arg2) {
  return window['go']['core']['App']['SaveProject'](arg1, arg2);
}

export function SaveProjectToPath(arg1, arg2) {
  return window['go']['core']['App']['SaveProjectToPath'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['core']['App']['SaveSettings'](arg1);
}

export function SelectDirectory(arg1) {
  return window['go']['core']['App']['SelectDirectory'](arg1);
}
