// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRecentProject(arg1:string,arg2:string):Promise<void>;

export function AutoSave(arg1:string):Promise<void>;

export function BlendImages(arg1:string):Promise<string>;

export function ClearAutoSave():Promise<void>;

export function ClearRecentProjects():Promise<void>;

export function CreateProject(arg1:string,arg2:string,arg3:string):Promise<string>;

export function EditImage(arg1:string):Promise<string>;

export function EnhancePrompt(arg1:string):Promise<string>;

export function ExportImage(arg1:string,arg2:string):Promise<string>;

export function FetchPrompts(arg1:boolean):Promise<string>;

export function GenerateImage(arg1:string):Promise<string>;

export function GetProjectMeta(arg1:string):Promise<string>;

export function GetRecentProjects():Promise<string>;

export function LoadAutoSave():Promise<string>;

export function LoadProject():Promise<string>;

export function LoadProjectFromPath(arg1:string):Promise<string>;

export function LoadSettings():Promise<string>;

export function RemoveBackground(arg1:string):Promise<string>;

export function RemoveRecentProject(arg1:string):Promise<void>;

export function SaveProject(arg1:string,arg2:string):Promise<string>;

export function SaveProjectToPath(arg1:string,arg2:string):Promise<void>;

export function SaveSettings(arg1:string):Promise<void>;

export function SelectDirectory(arg1:string):Promise<string>;
